{{- if and .Values.formae.auth.enabled (not .Values.formae.auth.basic.existingSecret) (not .Values.formae.existingConfig) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "formae.fullname" . }}-auth
  labels:
    {{- include "formae.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.formae.auth.basic.usernameKey }}: {{ required "formae.auth.basic.username is required when auth is enabled" .Values.formae.auth.basic.username | b64enc | quote }}
  {{ .Values.formae.auth.basic.passwordKey }}: {{ required "formae.auth.basic.password is required when auth is enabled" .Values.formae.auth.basic.password | b64enc | quote }}
{{- end }}
